# Generated by Django 4.2.11 on 2024-03-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_productcart_productcartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcart',
            options={'verbose_name': 'Карта товаров', 'verbose_name_plural': 'Карты товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.CharField(choices=[('Active', 'Активен'), ('Inactive', 'Неактивен')], max_length=20, verbose_name='Активность на сайте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена $'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
